### ISSUE TITLE
Redis & tile caching problem

### ISSUE THREAD

**Issue by jkjeon0329** [tilezen/tilequeue#207] opened 2017-05-12 10:30 UTC
![redis_problem](https://cloud.githubusercontent.com/assets/27664210/25994124/9928ec58-3747-11e7-83f9-ca84a9a106b1.png)

Last release have a redis caching problem in config.yaml

https://github.com/tilezen/tileserver/blob/4bce0a163189122d3a51847a6ae9e75d42456784/config.yaml.sample

My setting is below
Thanks.

postgresql:
  host: localhost
  port: 5432
  # multiple databases can be specified, and these are iterated
  # through to balance query loads. This is useful when connecting to
  # pgbouncer, which can dispatch to different back end databases
  # based on the name.
  dbnames: [osm]
  user: osm
  password: team39
queries:
  config: /home/map/mapzen/vector-datasource/queries.yaml
  template-path: /home/map/mapzen/vector-datasource/queries
  # whether to reload the jinja query templates. This should be off in
  # production.
  reload-templates: true

# format extensions to support
# buffered Mapbox Vector Tiles are also possible by specifying mvtb
formats: [json, topojson, mvt]
# buffer configuration, see tilequeue sample config for details
buffer: {}

server:
  host: localhost
  port: 8080
  debug: true
  reload: true
  threaded: false

# whether to include cors headers on responses
cors: true #false #true

# optional for health checks. This can be useful for monitoring to
# verify that the service is still running and can connect to the
# database.
health:
  # request path to listen for health checks
  url: /_health

# to cache tiles locally, enable a cache. This can be useful when
# experiencing timeouts for low or mid zoom ranges.
#store:
#   type: directory
#   #path: /home/map/mapzen/tileserver/vtiles
#   name: /home/map/mapzen/tileserver/vtiles #vtiles
cache:
   type: redis
   redis:
     url: redis://localhost:6379
#     cache-set-key: tilequeue.key.redis #tiles-of-interest
#    file:
#      prefix: /home/map/mapzen/tilequeue/tiles #directory_prefix

**Comment by iandees** [comment] 2017-05-12 12:33
This looks like a duplicate of https://github.com/tilezen/tileserver/issues/91, and since the problem appears to be in tileserver, I'm going to close it here.

**Closed by iandees** 2017-05-12 12:33 UTC
